In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## train AP

In [ ]:
train_AP =  pd.read_csv('/content/drive/MyDrive/kaggle/train/train_AP.csv')
truth = pd.read_csv('/content/BUU-LSPINE_spondylolisthesis/train/train_ground_truth.csv')

# Create a new column in XX dataframe with 'id' format of AP dataframe
truth['new_id'] = truth['id'].apply(lambda x: x.split('_')[0])

# Merge the dataframes
merged_df = pd.merge(train_AP, truth, how='left', left_on='id', right_on='new_id')

# If you want to drop the 'new_id' column after merge
merged_df = merged_df.drop(columns=['Unnamed: 0','new_id'])
merged_df['L'] = merged_df['id_y'].apply(lambda x : x.split('_')[-1])
train_AP_finish = merged_df.drop(columns=['id_y'])
train_AP_finish = train_AP_finish.rename(columns={'id_x':'id'})
train_AP_finish.head(),len(train_AP_finish)

(      id    L1a_1c    L1a_1r    L1a_2c    L1a_2r    L1b_1c    L1b_1r  \
 0  0.jpg  0.475247  0.075482  0.610531  0.075482  0.475247  0.145667
 1  0.jpg  0.475247  0.075482  0.610531  0.075482  0.475247  0.145667
 2  0.jpg  0.475247  0.075482  0.610531  0.075482  0.475247  0.145667
 3  0.jpg  0.475247  0.075482  0.610531  0.075482  0.475247  0.145667
 4  0.jpg  0.475247  0.075482  0.610531  0.075482  0.475247  0.145667

      L1b_2c    L1b_2r    L2a_1c  ...    L5b_1c    L5b_1r    L5b_2c    L5b_2r  \
 0  0.610531  0.145667  0.467669  ...  0.421466  0.545728  0.619579  0.545728
 1  0.610531  0.145667  0.467669  ...  0.421466  0.545728  0.619579  0.545728
 2  0.610531  0.145667  0.467669  ...  0.421466  0.545728  0.619579  0.545728
 3  0.610531  0.145667  0.467669  ...  0.421466  0.545728  0.619579  0.545728
 4  0.610531  0.145667  0.467669  ...  0.421466  0.545728  0.619579  0.545728

    S1a_1c  S1a_1r  S1a_2c  S1a_2r  class   L
 0     NaN     NaN     NaN     NaN      0  L1
 1     NaN     NaN     NaN     NaN      0  L2
 2     NaN     NaN     NaN     NaN      0  L3
 3     NaN     NaN     NaN     NaN      0  L4
 4     NaN     NaN     NaN     NaN      0  L5

 [5 rows x 47 columns],
 14230)

In [ ]:
train_AP_finish['class'] =train_AP_finish['class'].astype(str)

In [ ]:
from tqdm.notebook import tqdm
import numpy as np

In [ ]:
new_rows = []

# Iterate over rows
for index, row in tqdm(train_AP_finish.iterrows()):
    # Check if 'class' is not equal to '0'
    if row['class'] != '5':
        # Create 5 new rows for each row with 'class' not equal to '0'
        for _ in range(1):
            new_row = row.copy()
            # Iterate over each column
            # Add constant value between (-0.1) and (0.1)
            constant_value = np.random.uniform(-0.1, 0.1)
            for column in train_AP_finish.columns:
                if column not in ['id', 'class','L']:
                    # Multiply value between 0.95 and 1.05
                    new_row[column] = new_row[column] + constant_value*np.random.uniform(0.95, 1.05)
            new_rows.append(new_row)

# Append the new rows to the dataframe
train_AP_finish = train_AP_finish.append(new_rows, ignore_index=True)

0it [00:00, ?it/s]

<ipython-input-112-5b3298dd7297>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_AP_finish = train_AP_finish.append(new_rows, ignore_index=True)

In [ ]:
train_AP_finish[train_AP_finish['class']=='1']

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,class,L
14038,1012.jpg,0.485990,0.248454,0.630059,0.248454,0.485990,0.316294,0.630059,0.316294,0.490848,...,0.427517,0.641674,0.605888,0.641674,NaN,NaN,NaN,NaN,1,L4
14043,1020.jpg,0.369167,0.216896,0.611469,0.216896,0.369167,0.283683,0.611469,0.283683,0.379000,...,0.360579,0.606269,0.655843,0.606269,NaN,NaN,NaN,NaN,1,L4
14047,1045.jpg,0.429685,0.223671,0.602649,0.223671,0.429685,0.308919,0.602649,0.308919,0.454273,...,0.397521,0.617150,0.614357,0.617150,NaN,NaN,NaN,NaN,1,L3
14052,117.jpg,0.495768,0.219124,0.669827,0.219124,0.495768,0.316330,0.669827,0.316330,0.515273,...,0.429079,0.608490,0.619207,0.608490,NaN,NaN,NaN,NaN,1,L3
14058,1180.jpg,0.359345,0.094565,0.511979,0.094565,0.359345,0.167398,0.511979,0.167398,0.374215,...,0.393088,0.466819,0.585391,0.466819,NaN,NaN,NaN,NaN,1,L4
14062,1199.jpg,0.481794,0.249287,0.645748,0.249287,0.481794,0.328639,0.645748,0.328639,0.494720,...,0.412747,0.629528,0.606956,0.629528,NaN,NaN,NaN,NaN,1,L3
14067,1353.jpg,0.415741,0.178879,0.564504,0.178879,0.415741,0.257535,0.564504,0.257535,0.392027,...,0.343399,0.567062,0.510789,0.567062,NaN,NaN,NaN,NaN,1,L3
14073,1699.jpg,0.415400,0.246541,0.565054,0.246541,0.415400,0.333858,0.565054,0.333858,0.416336,...,0.432990,0.605123,0.617675,0.605123,NaN,NaN,NaN,NaN,1,L4
14078,172.jpg,0.381583,0.158984,0.520958,0.158984,0.381583,0.241414,0.520958,0.241414,0.400485,...,0.450186,0.524924,0.619922,0.524924,NaN,NaN,NaN,NaN,1,L4
14083,1903.jpg,0.440196,0.109316,0.606311,0.109316,0.440196,0.170717,0.606311,0.170717,0.432788,...,0.394770,0.515763,0.608658,0.515763,NaN,NaN,NaN,NaN,1,L4
14088,1942.jpg,0.483767,0.263567,0.610296,0.263567,0.483767,0.324098,0.610296,0.324098,0.491050,...,0.478836,0.627336,0.648991,0.627336,NaN,NaN,NaN,NaN,1,L4
14091,1943.jpg,0.433948,0.189239,0.575040,0.189239,0.433948,0.264251,0.575040,0.264251,0.403959,...,0.388951,0.562265,0.566190,0.562265,NaN,NaN,NaN,NaN,1,L2
14098,196.jpg,0.407775,0.196999,0.570724,0.196999,0.407775,0.259639,0.570724,0.259639,0.419638,...,0.434439,0.524245,0.618851,0.524245,NaN,NaN,NaN,NaN,1,L4
14103,437.jpg,0.373227,0.184751,0.542427,0.184751,0.373227,0.249310,0.542427,0.249310,0.373523,...,0.372831,0.582469,0.588217,0.582469,NaN,NaN,NaN,NaN,1,L4
14106,455.jpg,0.423470,0.298928,0.587336,0.298928,0.423470,0.366696,0.587336,0.366696,0.410798,...,0.376598,0.689681,0.583778,0.689681,NaN,NaN,NaN,NaN,1,L2
14113,494.jpg,0.415349,0.227273,0.569397,0.227273,0.415349,0.277111,0.569397,0.277111,0.402745,...,0.380027,0.583822,0.553202,0.583822,NaN,NaN,NaN,NaN,1,L4
14117,566.jpg,0.428374,0.294407,0.657458,0.294407,0.428374,0.352727,0.657458,0.352727,0.403787,...,0.289170,0.634138,0.567235,0.634138,NaN,NaN,NaN,NaN,1,L3
28268,1012.jpg,0.517665,0.281147,0.662593,0.280845,0.518389,0.346307,0.660899,0.348060,0.521721,...,0.458180,0.673628,0.636369,0.673713,NaN,NaN,NaN,NaN,1,L4
28273,1020.jpg,0.329981,0.174994,0.569312,0.173826,0.328155,0.242934,0.568919,0.242102,0.337390,...,0.319094,0.565740,0.614490,0.567105,NaN,NaN,NaN,NaN,1,L4
28277,1045.jpg,0.387080,0.183283,0.562701,0.183502,0.389197,0.267229,0.561911,0.266711,0.413019,...,0.356230,0.575586,0.570696,0.573755,NaN,NaN,NaN,NaN,1,L3
28282,117.jpg,0.420466,0.146461,0.597241,0.145646,0.425370,0.244658,0.597761,0.245415,0.443952,...,0.355568,0.534228,0.545659,0.535822,NaN,NaN,NaN,NaN,1,L3
28288,1180.jpg,0.361015,0.096212,0.513713,0.096154,0.360991,0.169086,0.513675,0.169011,0.375878,...,0.394671,0.468412,0.587082,0.468495,NaN,NaN,NaN,NaN,1,L4
28292,1199.jpg,0.552426,0.316188,0.711451,0.317506,0.546803,0.398017,0.713826,0.396679,0.559704,...,0.478535,0.699095,0.675907,0.697477,NaN,NaN,NaN,NaN,1,L3
28297,1353.jpg,0.425031,0.188179,0.574091,0.188934,0.424970,0.267041,0.574234,0.266981,0.401750,...,0.353331,0.576635,0.519930,0.576897,NaN,NaN,NaN,NaN,1,L3
28303,1699.jpg,0.377146,0.211668,0.530174,0.208756,0.377618,0.297660,0.529749,0.295842,0.378880,...,0.397544,0.568358,0.580736,0.567824,NaN,NaN,NaN,NaN,1,L4
28308,172.jpg,0.288252,0.072664,0.431277,0.069461,0.295048,0.153471,0.428985,0.156115,0.307099,...,0.357717,0.438955,0.527025,0.435838,NaN,NaN,NaN,NaN,1,L4
28313,1903.jpg,0.512548,0.178291,0.679162,0.184646,0.512172,0.243227,0.677871,0.243125,0.508463,...,0.464042,0.590093,0.679807,0.586092,NaN,NaN,NaN,NaN,1,L4
28318,1942.jpg,0.411849,0.192831,0.538395,0.191990,0.415484,0.257403,0.538746,0.254185,0.419181,...,0.412099,0.560556,0.578908,0.555939,NaN,NaN,NaN,NaN,1,L4
28321,1943.jpg,0.469789,0.224570,0.609607,0.224713,0.468923,0.300886,0.609521,0.298272,0.439104,...,0.425520,0.598201,0.602103,0.599114,NaN,NaN,NaN,NaN,1,L2
28328,196.jpg,0.340682,0.125439,0.501029,0.124188,0.333761,0.192234,0.502841,0.188322,0.347690,...,0.365059,0.454658,0.549039,0.457111,NaN,NaN,NaN,NaN,1,L4
28333,437.jpg,0.271778,0.084992,0.438519,0.085620,0.276949,0.149058,0.441195,0.149931,0.269477,...,0.275011,0.480647,0.486949,0.481445,NaN,NaN,NaN,NaN,1,L4
28336,455.jpg,0.514464,0.388650,0.677795,0.390687,0.515241,0.454884,0.681876,0.454759,0.505150,...,0.470055,0.782019,0.672057,0.780201,NaN,NaN,NaN,NaN,1,L2
28343,494.jpg,0.484227,0.302907,0.638651,0.299805,0.491320,0.350634,0.643193,0.352230,0.477106,...,0.452562,0.658932,0.622264,0.655818,NaN,NaN,NaN,NaN,1,L4
28347,566.jpg,0.419638,0.285182,0.648530,0.285579,0.419642,0.343947,0.648959,0.344138,0.394560,...,0.280686,0.624880,0.558057,0.625498,NaN,NaN,NaN,NaN,1,L3

## train LA

In [ ]:
train_LA =  pd.read_csv('/content/drive/MyDrive/kaggle/train/train_LA.csv')
truth = pd.read_csv('/content/BUU-LSPINE_spondylolisthesis/train/train_ground_truth.csv')
# Create a new column in XX dataframe with 'id' format of AP dataframe
truth['new_id'] = truth['id'].apply(lambda x: x.split('_')[0])

# Merge the dataframes
merged_df = pd.merge(train_LA, truth, how='left', left_on='id', right_on='new_id')

# If you want to drop the 'new_id' column after merge
merged_df = merged_df.drop(columns=['Unnamed: 0','new_id'])
merged_df['L'] = merged_df['id_y'].apply(lambda x : x.split('_')[-1])
merged_df = merged_df.drop(columns=['id_y'])
merged_df['class'] =  merged_df['class'].astype(str)
train_LA_finish = merged_df.copy()
train_LA_finish = train_LA_finish.rename(columns={'id_x':'id'})
train_LA_finish.head()

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,class,L
0,3000.jpg,0.39688,0.081835,0.618736,0.081835,0.39688,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.42822,0.593876,0.258535,0.642704,0.434374,0.548236,0,L1
1,3000.jpg,0.39688,0.081835,0.618736,0.081835,0.39688,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.42822,0.593876,0.258535,0.642704,0.434374,0.548236,0,L2
2,3000.jpg,0.39688,0.081835,0.618736,0.081835,0.39688,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.42822,0.593876,0.258535,0.642704,0.434374,0.548236,0,L3
3,3000.jpg,0.39688,0.081835,0.618736,0.081835,0.39688,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.42822,0.593876,0.258535,0.642704,0.434374,0.548236,0,L4
4,3000.jpg,0.39688,0.081835,0.618736,0.081835,0.39688,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.42822,0.593876,0.258535,0.642704,0.434374,0.548236,0,L5

In [ ]:
new_rows = []

# Iterate over rows
for index, row in tqdm(train_LA_finish.iterrows()):
    # Check if 'class' is not equal to '0'
    if row['class'] != '0':
        # Create 5 new rows for each row with 'class' not equal to '0'
        for _ in range(50):
            new_row = row.copy()
            # Add constant value between (-0.1) and (0.1)
            constant_value = np.random.uniform(-0.1, 0.1)
            # Iterate over each column
            for column in train_LA_finish.columns:
                if column not in ['id', 'class','L']:

                    # Multiply value between 0.95 and 1.05
                    new_row[column] = new_row[column] + constant_value* np.random.uniform(0.95, 1.05)

            new_rows.append(new_row)

# Append the new rows to the dataframe
train_LA_finish = train_LA_finish.append(new_rows, ignore_index=True)

0it [00:00, ?it/s]

<ipython-input-115-6bccd3cdaa72>:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_LA_finish = train_LA_finish.append(new_rows, ignore_index=True)

In [ ]:
train_LA_finish[train_LA_finish['class']=='0']

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,class,L
0,3000.jpg,0.396880,0.081835,0.618736,0.081835,0.396880,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.428220,0.593876,0.258535,0.642704,0.434374,0.548236,0,L1
1,3000.jpg,0.396880,0.081835,0.618736,0.081835,0.396880,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.428220,0.593876,0.258535,0.642704,0.434374,0.548236,0,L2
2,3000.jpg,0.396880,0.081835,0.618736,0.081835,0.396880,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.428220,0.593876,0.258535,0.642704,0.434374,0.548236,0,L3
3,3000.jpg,0.396880,0.081835,0.618736,0.081835,0.396880,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.428220,0.593876,0.258535,0.642704,0.434374,0.548236,0,L4
4,3000.jpg,0.396880,0.081835,0.618736,0.081835,0.396880,0.188593,0.618736,0.188593,0.308708,...,0.217434,0.593876,0.428220,0.593876,0.258535,0.642704,0.434374,0.548236,0,L5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,3757.jpg,0.498877,0.364351,0.616190,0.364351,0.498877,0.432137,0.616190,0.432137,0.491363,...,0.490892,0.738885,0.616933,0.738885,0.495062,0.770242,0.614322,0.716460,0,L1
1766,3757.jpg,0.498877,0.364351,0.616190,0.364351,0.498877,0.432137,0.616190,0.432137,0.491363,...,0.490892,0.738885,0.616933,0.738885,0.495062,0.770242,0.614322,0.716460,0,L2
1770,3793.jpg,0.537818,0.241433,0.650506,0.241433,0.537818,0.319133,0.650506,0.319133,0.543501,...,0.487256,0.658165,0.593914,0.658165,0.490798,0.704367,0.592929,0.646611,0,L1
1771,3793.jpg,0.537818,0.241433,0.650506,0.241433,0.537818,0.319133,0.650506,0.319133,0.543501,...,0.487256,0.658165,0.593914,0.658165,0.490798,0.704367,0.592929,0.646611,0,L2
1774,3793.jpg,0.537818,0.241433,0.650506,0.241433,0.537818,0.319133,0.650506,0.319133,0.543501,...,0.487256,0.658165,0.593914,0.658165,0.490798,0.704367,0.592929,0.646611,0,L5

In [ ]:
train_LA_finish[train_LA_finish['class']=='3']

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,class,L
538,2030.jpg,0.586202,0.257940,0.710294,0.257940,0.586202,0.349588,0.710294,0.349588,0.536459,...,0.486402,0.650122,0.591366,0.650122,0.487548,0.690257,0.593602,0.634407,3,L4
543,2048.jpg,0.324668,0.196992,0.491415,0.196992,0.324668,0.284190,0.491415,0.284190,0.282603,...,0.374377,0.651461,0.562510,0.651461,0.437675,0.678290,0.594798,0.586274,3,L4
547,2050.jpg,0.328054,0.252150,0.508173,0.252150,0.328054,0.324410,0.508173,0.324410,0.310154,...,0.455154,0.631371,0.659037,0.631371,0.492952,0.656280,0.669753,0.593604,3,L3
548,2050.jpg,0.328054,0.252150,0.508173,0.252150,0.328054,0.324410,0.508173,0.324410,0.310154,...,0.455154,0.631371,0.659037,0.631371,0.492952,0.656280,0.669753,0.593604,3,L4
553,2088.jpg,0.573157,0.049510,0.694902,0.049510,0.573157,0.131982,0.694902,0.131982,0.536223,...,0.516590,0.449650,0.628359,0.449650,0.530984,0.481564,0.632695,0.421570,3,L4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15970,3757.jpg,0.560263,0.430758,0.677683,0.425419,0.562543,0.496584,0.682011,0.498225,0.555740,...,0.557029,0.805268,0.679964,0.805488,0.556371,0.836553,0.679317,0.778803,3,L3
15971,3757.jpg,0.514671,0.379824,0.630947,0.380276,0.514385,0.447772,0.632143,0.446940,0.506865,...,0.505678,0.754281,0.632070,0.754436,0.510080,0.785618,0.629307,0.731753,3,L3
15972,3757.jpg,0.426499,0.294510,0.545130,0.294917,0.430182,0.361627,0.544270,0.361196,0.422255,...,0.420186,0.664167,0.545211,0.664631,0.421796,0.698094,0.541574,0.642192,3,L3
15973,3757.jpg,0.499768,0.365185,0.617094,0.365211,0.499708,0.433004,0.617075,0.432993,0.492248,...,0.491748,0.739742,0.617766,0.739711,0.495966,0.771133,0.615219,0.717296,3,L3
15974,3757.jpg,0.551127,0.415389,0.667145,0.416289,0.549469,0.483240,0.671296,0.486684,0.542691,...,0.545095,0.792381,0.667954,0.793130,0.546878,0.825588,0.669018,0.769966,3,L3

In [ ]:
train_LA_finish[train_LA_finish['class']=='1']

Empty DataFrame
Columns: [id, L1a_1c, L1a_1r, L1a_2c, L1a_2r, L1b_1c, L1b_1r, L1b_2c, L1b_2r, L2a_1c, L2a_1r, L2a_2c, L2a_2r, L2b_1c, L2b_1r, L2b_2c, L2b_2r, L3a_1c, L3a_1r, L3a_2c, L3a_2r, L3b_1c, L3b_1r, L3b_2c, L3b_2r, L4a_1c, L4a_1r, L4a_2c, L4a_2r, L4b_1c, L4b_1r, L4b_2c, L4b_2r, L5a_1c, L5a_1r, L5a_2c, L5a_2r, L5b_1c, L5b_1r, L5b_2c, L5b_2r, S1a_1c, S1a_1r, S1a_2c, S1a_2r, class, L]
Index: []

[0 rows x 47 columns]

## test AP

In [ ]:
import numpy as np

In [ ]:
test_AP = pd.read_csv('/content/drive/MyDrive/kaggle/test/test_AP.csv').drop(columns=['Unnamed: 0'])
test_AP_left = test_AP.copy().reindex(test_AP.index.repeat(5)).reset_index(drop=True)

# Create new column 'L' with values L1, L2, L3, L4, L5
test_AP_left['L'] = np.resize(['L1', 'L2', 'L3', 'L4', 'L5'], len(test_AP_left))
test_AP_finish = test_AP_left.copy()
test_AP_finish['id'] = test_AP_finish['id'] + '_' +test_AP_finish['L']

In [ ]:
test_AP_finish.head()

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5a_2r,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,L
0,t120.jpg_L1,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.488745,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L1
1,t120.jpg_L2,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.488745,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L2
2,t120.jpg_L3,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.488745,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L3
3,t120.jpg_L4,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.488745,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L4
4,t120.jpg_L5,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.488745,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L5

## test LA

In [ ]:
test_LA = pd.read_csv('/content/drive/MyDrive/kaggle/test/test_LA.csv')
test_LA_left = test_LA.copy().reindex(test_LA.index.repeat(5)).reset_index(drop=True).drop(columns=['Unnamed: 0'])

# Create new column 'L' with values L1, L2, L3, L4, L5
test_LA_left['L'] = np.resize(['L1', 'L2', 'L3', 'L4', 'L5'], len(test_LA_left))
test_LA_finish = test_LA_left.copy()
test_LA_finish['id'] = test_LA_finish['id'] + '_' +test_LA_finish['L']
print(len(test_LA_finish))
test_LA_finish.head()

4475

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5a_2r,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,L
0,t0.jpg_L1,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.577823,0.35886,0.663488,0.471924,0.663488,0.372348,0.70469,0.485956,0.638903,L1
1,t0.jpg_L2,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.577823,0.35886,0.663488,0.471924,0.663488,0.372348,0.70469,0.485956,0.638903,L2
2,t0.jpg_L3,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.577823,0.35886,0.663488,0.471924,0.663488,0.372348,0.70469,0.485956,0.638903,L3
3,t0.jpg_L4,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.577823,0.35886,0.663488,0.471924,0.663488,0.372348,0.70469,0.485956,0.638903,L4
4,t0.jpg_L5,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.577823,0.35886,0.663488,0.471924,0.663488,0.372348,0.70469,0.485956,0.638903,L5

## Train

In [ ]:
!pip install autogluon.tabular[all]

#Train AP

In [ ]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [ ]:
label = 'class'
print("Summary of class variable: \n", merged_df[train_AP_finish].describe())

In [ ]:
test_AP_pre = test_AP_finish.drop(columns=['id'])
train_AP_pre = train_AP_finish.drop(columns=['id'])

In [ ]:
predictor = TabularPredictor(label='class').fit(train_data=train_AP_pre)
predictions = predictor.predict(test_AP_pre)
test_AP_finish['class'] = predictions
test_AP_finish

No path specified. Models will be saved in: "AutogluonModels/ag-20230617_162814/"
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20230617_162814/"
AutoGluon Version:  0.8.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Apr 29 09:15:28 UTC 2023
Disk Space Avail:   138.11 GB / 179.07 GB (77.1%)
Train Data Rows:    14271
Train Data Columns: 45
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	3 unique label values:  ['0', '1', '2']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    86958.93 MB
	Train Data (Original)  Memory Usage: 5.87 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 4): ['S1a_1c', 'S1a_1r', 'S1a_2c', 'S1a_2r']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 40 | ['L1a_1c', 'L1a_1r', 'L1a_2c', 'L1a_2r', 'L1b_1c', ...]
		('object', []) :  1 | ['L']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) :  1 | ['L']
		('float', [])    : 40 | ['L1a_1c', 'L1a_1r', 'L1a_2c', 'L1a_2r', 'L1b_1c', ...]
	1.0s = Fit runtime
	41 features in original data used to generate 41 features in processed data.
	Train Data (Processed) Memory Usage: 4.58 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 1.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 12843, Val Rows: 1428
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.9944	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.9944	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.16s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 3: early stopping
	0.9944	 = Validation score   (accuracy)
	12.46s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.9958	 = Validation score   (accuracy)
	3.13s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM ...
	0.9951	 = Validation score   (accuracy)
	2.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.9888	 = Validation score   (accuracy)
	1.49s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.9895	 = Validation score   (accuracy)
	1.46s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost ...
	0.9944	 = Validation score   (accuracy)
	3.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.9937	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.9944	 = Validation score   (accuracy)
	0.83s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: XGBoost ...
	0.9951	 = Validation score   (accuracy)
	2.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.9944	 = Validation score   (accuracy)
	6.55s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.9944	 = Validation score   (accuracy)
	5.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	0.9958	 = Validation score   (accuracy)
	0.87s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 45.1s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20230617_162814/")

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,L,class
0,t120.jpg_L1,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L1,0
1,t120.jpg_L2,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L2,0
2,t120.jpg_L3,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L3,0
3,t120.jpg_L4,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L4,0
4,t120.jpg_L5,0.401268,0.165478,0.535148,0.165478,0.401268,0.226797,0.535148,0.226797,0.404185,...,0.397427,0.549606,0.556771,0.549606,NaN,NaN,NaN,NaN,L5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,t992.jpg_L1,0.284706,0.104945,0.422441,0.104945,0.284706,0.162138,0.422441,0.162138,0.293961,...,0.298741,0.498090,0.474677,0.498090,NaN,NaN,NaN,NaN,L1,0
521,t992.jpg_L2,0.284706,0.104945,0.422441,0.104945,0.284706,0.162138,0.422441,0.162138,0.293961,...,0.298741,0.498090,0.474677,0.498090,NaN,NaN,NaN,NaN,L2,0
522,t992.jpg_L3,0.284706,0.104945,0.422441,0.104945,0.284706,0.162138,0.422441,0.162138,0.293961,...,0.298741,0.498090,0.474677,0.498090,NaN,NaN,NaN,NaN,L3,0
523,t992.jpg_L4,0.284706,0.104945,0.422441,0.104945,0.284706,0.162138,0.422441,0.162138,0.293961,...,0.298741,0.498090,0.474677,0.498090,NaN,NaN,NaN,NaN,L4,0
524,t992.jpg_L5,0.284706,0.104945,0.422441,0.104945,0.284706,0.162138,0.422441,0.162138,0.293961,...,0.298741,0.498090,0.474677,0.498090,NaN,NaN,NaN,NaN,L5,0

In [ ]:
predictor.feature_importance(train_AP_finish)

These features in provided data are not utilized by the predictor and will be ignored: ['id', 'S1a_1c', 'S1a_1r', 'S1a_2c', 'S1a_2r']
Computing feature importance via permutation shuffling for 41 features using 5000 rows with 5 shuffle sets...
	37.12s	= Expected runtime (7.42s per shuffle set)
	28.81s	= Actual runtime (Completed 5 of 5 shuffle sets)

        importance    stddev   p_value  n  p99_high   p99_low
L          0.00584  0.001108  0.000148  5  0.008122  0.003558
L5b_2r     0.00032  0.000228  0.017460  5  0.000790 -0.000150
L5b_2c     0.00020  0.000141  0.017055  5  0.000491 -0.000091
L4a_1c     0.00016  0.000167  0.049650  5  0.000505 -0.000185
L1b_2r     0.00016  0.000167  0.049650  5  0.000505 -0.000185
L4a_2c     0.00016  0.000261  0.120991  5  0.000697 -0.000377
L1b_2c     0.00016  0.000167  0.049650  5  0.000505 -0.000185
L5a_2c     0.00012  0.000179  0.104000  5  0.000488 -0.000248
L5a_1r     0.00012  0.000110  0.035242  5  0.000346 -0.000106
L5b_1c     0.00008  0.000110  0.088904  5  0.000306 -0.000146
L5a_1c     0.00008  0.000110  0.088904  5  0.000306 -0.000146
L1a_1c     0.00008  0.000110  0.088904  5  0.000306 -0.000146
L1a_2c     0.00008  0.000179  0.186950  5  0.000448 -0.000288
L1b_1c     0.00008  0.000110  0.088904  5  0.000306 -0.000146
L2a_1c     0.00008  0.000110  0.088904  5  0.000306 -0.000146
L2a_2c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4a_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L1a_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L5b_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L5a_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L1b_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L2a_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4b_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4b_2c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4b_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4b_1c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3b_1c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L2b_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L4a_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L2a_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3b_2c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L1a_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3a_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3a_2c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3a_1r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3a_1c     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L2b_2r     0.00004  0.000089  0.186950  5  0.000224 -0.000144
L3b_2r     0.00000  0.000000  0.500000  5  0.000000  0.000000
L3b_1r     0.00000  0.000000  0.500000  5  0.000000  0.000000
L2b_2c     0.00000  0.000000  0.500000  5  0.000000  0.000000
L2b_1c     0.00000  0.000000  0.500000  5  0.000000  0.000000

In [ ]:
train_AP_finish[:10]

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,class,L
0,0.jpg,0.475247,0.075482,0.610531,0.075482,0.475247,0.145667,0.610531,0.145667,0.467669,...,0.421466,0.545728,0.619579,0.545728,NaN,NaN,NaN,NaN,0,L1
1,0.jpg,0.475247,0.075482,0.610531,0.075482,0.475247,0.145667,0.610531,0.145667,0.467669,...,0.421466,0.545728,0.619579,0.545728,NaN,NaN,NaN,NaN,0,L2
2,0.jpg,0.475247,0.075482,0.610531,0.075482,0.475247,0.145667,0.610531,0.145667,0.467669,...,0.421466,0.545728,0.619579,0.545728,NaN,NaN,NaN,NaN,0,L3
3,0.jpg,0.475247,0.075482,0.610531,0.075482,0.475247,0.145667,0.610531,0.145667,0.467669,...,0.421466,0.545728,0.619579,0.545728,NaN,NaN,NaN,NaN,0,L4
4,0.jpg,0.475247,0.075482,0.610531,0.075482,0.475247,0.145667,0.610531,0.145667,0.467669,...,0.421466,0.545728,0.619579,0.545728,NaN,NaN,NaN,NaN,0,L5
5,1.jpg,0.493474,0.366567,0.610131,0.366567,0.493474,0.431048,0.610131,0.431048,0.507229,...,0.471789,0.734705,0.631581,0.734705,NaN,NaN,NaN,NaN,0,L1
6,1.jpg,0.493474,0.366567,0.610131,0.366567,0.493474,0.431048,0.610131,0.431048,0.507229,...,0.471789,0.734705,0.631581,0.734705,NaN,NaN,NaN,NaN,0,L2
7,1.jpg,0.493474,0.366567,0.610131,0.366567,0.493474,0.431048,0.610131,0.431048,0.507229,...,0.471789,0.734705,0.631581,0.734705,NaN,NaN,NaN,NaN,0,L3
8,1.jpg,0.493474,0.366567,0.610131,0.366567,0.493474,0.431048,0.610131,0.431048,0.507229,...,0.471789,0.734705,0.631581,0.734705,NaN,NaN,NaN,NaN,0,L4
9,1.jpg,0.493474,0.366567,0.610131,0.366567,0.493474,0.431048,0.610131,0.431048,0.507229,...,0.471789,0.734705,0.631581,0.734705,NaN,NaN,NaN,NaN,0,L5

In [ ]:
test_AP_predict = test_AP_finish[['id','class']].copy()
test_AP_predict

              id class
0    t120.jpg_L1     0
1    t120.jpg_L2     0
2    t120.jpg_L3     0
3    t120.jpg_L4     0
4    t120.jpg_L5     0
..           ...   ...
520  t992.jpg_L1     0
521  t992.jpg_L2     0
522  t992.jpg_L3     0
523  t992.jpg_L4     0
524  t992.jpg_L5     0

[525 rows x 2 columns]

# train LA

In [ ]:
test_LA_pre = train_LA_finish.drop(columns=['id'])
train_LA_pre = train_LA_finish.drop(columns=['id'])

In [ ]:
predictor = TabularPredictor(label='class').fit(train_data=train_LA_pre)
predictions = predictor.predict(test_LA_pre)
test_LA_finish['class'] = predictions
test_LA_finish

No path specified. Models will be saved in: "AutogluonModels/ag-20230617_162955/"
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20230617_162955/"
AutoGluon Version:  0.8.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Apr 29 09:15:28 UTC 2023
Disk Space Avail:   138.07 GB / 179.07 GB (77.1%)
Train Data Rows:    4655
Train Data Columns: 45
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	3 unique label values:  ['0', '3', '4']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    86348.75 MB
	Train Data (Original)  Memory Usage: 1.91 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 44 | ['L1a_1c', 'L1a_1r', 'L1a_2c', 'L1a_2r', 'L1b_1c', ...]
		('object', []) :  1 | ['L']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) :  1 | ['L']
		('float', [])    : 44 | ['L1a_1c', 'L1a_1r', 'L1a_2c', 'L1a_2r', 'L1b_1c', ...]
	0.2s = Fit runtime
	45 features in original data used to generate 45 features in processed data.
	Train Data (Processed) Memory Usage: 1.64 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.21s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.10741138560687433, Train Rows: 4155, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.692	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.782	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.946	 = Validation score   (accuracy)
	4.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ...

[1000]	valid_set's multi_error: 0.12

	0.888	 = Validation score   (accuracy)
	5.87s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBM ...
	0.886	 = Validation score   (accuracy)
	3.08s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.834	 = Validation score   (accuracy)
	1.03s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.836	 = Validation score   (accuracy)
	1.37s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost ...
	0.882	 = Validation score   (accuracy)
	45.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.844	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.84	 = Validation score   (accuracy)
	0.77s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost ...
	0.894	 = Validation score   (accuracy)
	7.83s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.976	 = Validation score   (accuracy)
	21.44s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...

[1000]	valid_set's multi_error: 0.11

	0.894	 = Validation score   (accuracy)
	17.33s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	0.986	 = Validation score   (accuracy)
	0.83s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 112.6s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20230617_162955/")

,id,L1a_1c,L1a_1r,L1a_2c,L1a_2r,L1b_1c,L1b_1r,L1b_2c,L1b_2r,L2a_1c,...,L5b_1c,L5b_1r,L5b_2c,L5b_2r,S1a_1c,S1a_1r,S1a_2c,S1a_2r,L,class
0,t0.jpg_L1,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.358860,0.663488,0.471924,0.663488,0.372348,0.704690,0.485956,0.638903,L1,0
1,t0.jpg_L2,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.358860,0.663488,0.471924,0.663488,0.372348,0.704690,0.485956,0.638903,L2,0
2,t0.jpg_L3,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.358860,0.663488,0.471924,0.663488,0.372348,0.704690,0.485956,0.638903,L3,0
3,t0.jpg_L4,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.358860,0.663488,0.471924,0.663488,0.372348,0.704690,0.485956,0.638903,L4,0
4,t0.jpg_L5,0.502088,0.218853,0.644152,0.218853,0.502088,0.321908,0.644152,0.321908,0.440128,...,0.358860,0.663488,0.471924,0.663488,0.372348,0.704690,0.485956,0.638903,L5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4470,t999.jpg_L1,0.506728,0.131119,0.666690,0.131119,0.506728,0.236162,0.666690,0.236162,0.454731,...,0.369909,0.634904,0.513259,0.634904,0.390999,0.693974,0.515277,0.612066,L1,4
4471,t999.jpg_L2,0.506728,0.131119,0.666690,0.131119,0.506728,0.236162,0.666690,0.236162,0.454731,...,0.369909,0.634904,0.513259,0.634904,0.390999,0.693974,0.515277,0.612066,L2,4
4472,t999.jpg_L3,0.506728,0.131119,0.666690,0.131119,0.506728,0.236162,0.666690,0.236162,0.454731,...,0.369909,0.634904,0.513259,0.634904,0.390999,0.693974,0.515277,0.612066,L3,4
4473,t999.jpg_L4,0.506728,0.131119,0.666690,0.131119,0.506728,0.236162,0.666690,0.236162,0.454731,...,0.369909,0.634904,0.513259,0.634904,0.390999,0.693974,0.515277,0.612066,L4,4
4474,t999.jpg_L5,0.506728,0.131119,0.666690,0.131119,0.506728,0.236162,0.666690,0.236162,0.454731,...,0.369909,0.634904,0.513259,0.634904,0.390999,0.693974,0.515277,0.612066,L5,4

In [ ]:
test_LA_finish[['id','class']]
test_LA_predict = test_LA_finish[['id','class']].copy()
test_LA_predict

               id class
0       t0.jpg_L1     0
1       t0.jpg_L2     0
2       t0.jpg_L3     0
3       t0.jpg_L4     0
4       t0.jpg_L5     0
...           ...   ...
4470  t999.jpg_L1     4
4471  t999.jpg_L2     4
4472  t999.jpg_L3     4
4473  t999.jpg_L4     4
4474  t999.jpg_L5     4

[4475 rows x 2 columns]

In [ ]:
test_submit = pd.concat([test_AP_predict, test_LA_predict])

In [ ]:
test_submit[test_submit['class']=='1']

Empty DataFrame
Columns: [id, class]
Index: []

In [ ]:
test_submit.to_csv('submission_3_sent_thirftime.csv', index=False)

In [ ]:
test_submit[test_submit['class']==2]

Empty DataFrame
Columns: [id, class]
Index: []